name: freefeos_example
description: "Demonstrates how to use the freefeos plugin."
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  freefeos:
    path: ../
  cupertino_icons: ^1.0.8
  multi_builder: ^1.0.0
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
