name: freefeos
description: "FreeFEOS is a Flutter plugin, a simple Flutter library operating system and an advanced Flutter development framework that can provide many advanced features for applications."
version: 0.2.2
homepage: https://github.com/freefeos/freefeos
repository: https://github.com/freefeos/freefeos
issue_tracker: https://github.com/freefeos/freefeos/issues
documentation: https://github.com/freefeos/freefeos/blob/master/README.md

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_plugin_android_lifecycle: ^2.0.22
  flutter_rust_bridge: ^2.4.0
  irondash_engine_context: ^0.5.4
  irondash_message_channel: ^0.7.0
  vm_service: ^14.2.5
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.1
  url_launcher: ^6.3.0
  flutter_adaptive_scaffold: ^0.3.1
  animations: ^2.0.11
  logging: ^1.2.0
  stack_trace: ^1.11.1
  super_clipboard: ^0.8.22
  toastification: ^2.2.0
  device_info_plus: ^10.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffi: ^2.1.3
  ffigen: ^14.0.1
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.freefeos.freefeos
        dartPluginClass: FreeFEOSRegister
        pluginClass: FreeFEOSEmbedder
        ffiPlugin: true
      ios:
        dartPluginClass: FreeFEOSRegister
        pluginClass: FreeFEOSEmbedder
        ffiPlugin: true
      linux:
        dartPluginClass: FreeFEOSRegister
        ffiPlugin: true
      macos:
        dartPluginClass: FreeFEOSRegister
        ffiPlugin: true
      windows:
        dartPluginClass: FreeFEOSRegister
        ffiPlugin: true
      web:
        fileName: freefeos_web.dart
        pluginClass: FreeFEOSRegister
        ffiPlugin: true
  assets:
    - AUTHORS
    - LICENSE
    - README.md
    - CHANGELOG.md
    - screenshot.png

flutter_intl:
  enabled: true
  class_name: IntlLocalizations
  main_locale: zh
  arb_dir: lib/src/l10n
  output_dir: lib/src/intl

screenshots:
  - description: "Screenshots 0"
    path: screenshot.png

topics:
  - framework
  - flutter
  - libraryos
