name: freefeos
description: "FreeFEOS"
version: 0.1.0
homepage: https://github.com/FreeFEOS/FreeFEOS
repository: https://github.com/FreeFEOS/FreeFEOS
issue_tracker: https://github.com/FreeFEOS/FreeFEOS/issues
documentation: https://github.com/FreeFEOS/FreeFEOS/blob/master/README.md

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: ^2.3.0
  flutter_plugin_android_lifecycle: ^2.0.21
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  vm_service: ^14.2.1
  shared_preferences: ^2.3.2
  sensors_plus: ^6.0.0
  package_info_plus: ^8.0.1
  url_launcher: ^6.3.0
  flutter_adaptive_scaffold: ^0.2.1
  animations: ^2.0.11
  logging: ^1.2.0
  stack_trace: ^1.11.1
  super_clipboard: ^0.8.19
  toastification: ^2.1.0
  device_info_plus: ^10.1.2
  win32: ^5.5.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffi: ^2.1.3
  ffigen: ^13.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.freefeos.freefeos
        dartPluginClass: FreeFEOSRegister
        pluginClass: FreeFEOSEmbedder
        ffiPlugin: true
      ios:
        dartPluginClass: FreeFEOSRegister
        pluginClass: FreeFEOSEmbedder
        ffiPlugin: true
      linux:
        dartPluginClass: FreeFEOSRegister
        ffiPlugin: true
      macos:
        dartPluginClass: FreeFEOSRegister
        ffiPlugin: true
      windows:
        dartPluginClass: FreeFEOSRegister
        ffiPlugin: true
  assets:
    - AUTHORS
    - LICENSE
    - README.md
    - CHANGELOG.md
    - screenshot.png

flutter_intl:
  enabled: true
  class_name: IntlLocalizations
  main_locale: zh
  arb_dir: lib/src/l10n
  output_dir: lib/src/intl

screenshots:
  - description: "Screenshots 0"
    path: screenshot.png

topics:
  - framework
  - flutter
  - libraryos
